config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'
  get '/gallery', to: 'app/front#gallery'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :conferences do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :post_categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :posts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      get '/save', action: :save
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    scope :blog do
      get '(page/:page)', to: 'blog#blog', as: :blog
      get '/search/(page/:page)', to: 'blog#search', as: :search
      get '/saved', to: 'blog#saved_posts', as: :saved_posts
      get '/:permalink', to: 'blog#show', as: :show_post
      get '/:permalink/save', to: 'blog#save', as: :save_post
      post '/:permalink/comment', to: 'blog#post_comment', as: :post_comment
      delete '/:permalink/comment/:comment_id', to: 'blog#delete_comment', as: :delete_comment
    end

    resources :images do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
end

app/models/conference.rb
# Conference Model
class Conference < ActiveRecord::Base
  include ActivityHistory
  include CloneRecord

  validates_presence_of :city, :place, :dates

  # Fields for the search form in the navbar
  def self.search_field
    :city_or_place_or_dates_cont
  end
end

app/controllers/admin/conferences_controller.rb
module Admin
  # ConferencesController
  class ConferencesController < AdminController
    before_action :set_conference, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /conferences
    def index
      @q = Conference.ransack(params[:q])
      conferences = @q.result(distinct: true)
      @objects = conferences.page(@current_page)
      @total = conferences.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to admin_conferences_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /conferences/1
    def show
    end

    # GET /conferences/new
    def new
      if Conference.count >= 3
        redirect_to admin_conferences_path,
                    notice: 'Solo pueden haber dos fechas de conferencias.\nEdite o elimine una.'
      end
      @conference = Conference.new

    end

    # GET /conferences/1/edit
    def edit
    end

    # POST /conferences
    def create
      @conference = Conference.new(conference_params)

      if @conference.save
        redirect(@conference, params)
      else
        render :new
      end
    end

    # PATCH/PUT /conferences/1
    def update
      if @conference.update(conference_params)
        redirect(@conference, params)
      else
        render :edit
      end
    end

    def clone
      @conference = Conference.clone_record params[:conference_id]

      if @conference.save
        redirect_to admin_conferences_path
      else
        render :new
      end
    end

    # DELETE /conferences/1
    def destroy
      @conference.destroy
      redirect_to admin_conferences_path, notice: actions_messages(@conference)
    end

    def destroy_multiple
      Conference.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_conferences_path(page: @current_page, search: @query),
        notice: actions_messages(Conference.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def conference_params
      params.require(:conference).permit(:city, :place, :dates, :hours)
    end

    def show_history
      get_history(Conference)
    end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/admin/conferences/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class('md-light')
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: 'height: {{windowHeight}}px;' }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t('keppler.titles.history')
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }

app/views/admin/conferences/_form.html.haml
.wrapper
  .wrapper-body.container
    .actions
      = link_to admin_conferences_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
        = material_icon.md_18.arrow_back.css_class("md-dark")
    .wrapper-inputs
      .card
        .card-content
          = simple_form_for [:admin, @conference] do |f|
            .row
              = f.input :city, label: 'Ciudad'
              = f.input :place, label: 'Lugar de la conferencia'
              = f.input :dates, label: '¿Entre qué dias se hará el evento?'

              .form-actions.right
                = f.button :submit, t("keppler.actions.save"), name: '_save'
      .card
        .card-content
          %h4 Ejemplo
          %p
            %strong Ciudad:
            Venezuela (Caracas)
          %p
            %strong Lugar de la conferencia:
            Hotel Lidotel
          %p
            %strong ¿Entre qué dias se hará el evento?
            Del 5 al 9 de Julio.

app/views/admin/conferences/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Conference
			= link_to edit_admin_conference_path(@conference), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label Ciudad
				.display-value= @conference.city
			%li.list-row
				.display-label Lugar de la conferencia
				.display-value= @conference.place
			%li.list-row
				.display-label ¿Entre qué dias se hará el evento?
				.display-value= @conference.dates
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_conferences_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/conferences/_listing.html.haml
%tr{ id: "row-#{conference.id}" }
	- if can? :destroy_multiple, Conference
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_conference_path(conference), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{conference.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{conference.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{conference.id}" }

		%td{style:"width: 30%"}
			= link_to "", admin_conference_path(conference, search: @query), remote: true, class: "show-row"
			%span
				= conference.city
		%td{style:"width: 30%"}
			= link_to "", admin_conference_path(conference, search: @query), remote: true, class: "show-row"
			%span
				= conference.dates
	- if (can? :clone, Conference) && (Conference.count < 2)
		%td{style:"width: 5%"}
			= link_to admin_conference_clone_path(conference), class: "btn-floating waves-effect btn-flat" do
				= material_icon.md_24.content_copy.css_class("md-dark")
	%td{style:"width: 5%"}
		= link_to admin_conference_path(conference), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/conferences/edit.html.haml
= title(t('keppler.titles.edit', model: "Conferences"))
= render 'form'

app/views/admin/conferences/index.html.haml
= title(t('keppler.titles.index', model: "Conferences"))
.listing.col.l9.m12.s12
	- if (can? :new, model) && (model.count < 3)
		= link_to new_admin_conference_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |conference|
				= render 'listing', conference: conference
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.conferences"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if (can? :new, model) && (model.count < 3)
	= link_to new_admin_conference_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/conferences/new.html.haml
= title(t('keppler.titles.new', model: "Conferences"))
= render 'form'

app/views/admin/conferences/show.html.haml
= title(t('keppler.titles.show', model: "Conferences"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Conference
				= link_to admin_conference_path(@conference), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Conference
				= link_to edit_admin_conference_path(@conference), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_conferences_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label Ciudad
						.display-value.fs-body-1.tc-black-2= @conference.city.to_s.humanize
					%li.list-row
						.display-label Lugar de la conferencia
						.display-value.fs-body-1.tc-black-2= @conference.place.to_s.humanize
					%li.list-row
						.display-label ¿Entre qué dias se hará el evento?
						.display-value.fs-body-1.tc-black-2= @conference.dates.to_s.humanize

app/views/admin/conferences/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@conference.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");