config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'
  get '/gallery', to: 'app/front#gallery'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :conferences do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :post_categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :posts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      get '/save', action: :save
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    scope :blog do
      get '(page/:page)', to: 'blog#blog', as: :blog
      get '/search/(page/:page)', to: 'blog#search', as: :search
      get '/saved', to: 'blog#saved_posts', as: :saved_posts
      get '/:permalink', to: 'blog#show', as: :show_post
      get '/:permalink/save', to: 'blog#save', as: :save_post
      post '/:permalink/comment', to: 'blog#post_comment', as: :post_comment
      delete '/:permalink/comment/:comment_id', to: 'blog#delete_comment', as: :delete_comment
    end

    resources :images do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
end

app/models/post_category.rb
# PostCategory Model
class PostCategory < ActiveRecord::Base
  include ActivityHistory
  include CloneRecord

  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :posts

  # Fields for the search form in the navbar
  def self.search_field
    :name_cont
  end
end

app/controllers/admin/post_categories_controller.rb
module Admin
  # PostCategoriesController
  class PostCategoriesController < AdminController
    before_action :set_post_category, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /post_categories
    def index
      @q = PostCategory.ransack(params[:q])
      post_categories = @q.result(distinct: true)
      @objects = post_categories.page(@current_page)
      @total = post_categories.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to post_categories_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /post_categories/1
    def show
    end

    # GET /post_categories/new
    def new
      @post_category = PostCategory.new
    end

    # GET /post_categories/1/edit
    def edit
    end

    # POST /post_categories
    def create
      @post_category = PostCategory.new(post_category_params)

      if @post_category.save
        redirect(@post_category, params)
      else
        render :new
      end
    end

    # PATCH/PUT /post_categories/1
    def update
      if @post_category.update(post_category_params)
        redirect(@post_category, params)
      else
        render :edit
      end
    end

    # DELETE /post_categories/1
    def destroy
      @post_category.destroy
      redirect_to admin_post_categories_path, notice: actions_messages(@post_category)
    end

    def destroy_multiple
      PostCategory.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_post_categories_path(page: @current_page, search: @query),
        notice: actions_messages(PostCategory.new)
      )
    end

    def clone
      @post_category = PostCategory.clone_record params[:post_category_id]

      if @post_category.save
        redirect_to admin_post_categories_path
      else
        render :new
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post_category
      @post_category = PostCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_category_params
      params.require(:post_category).permit(:name)
    end

    def show_history
      get_history(PostCategory)
    end
  end
end

app/views/admin/post_categories/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class('md-light')
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: 'height: {{windowHeight}}px;' }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t('keppler.titles.history')
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }

app/views/admin/post_categories/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_post_categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @post_category] do |f|
						.row
							= f.input :name

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: '_save'
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'

app/views/admin/post_categories/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, PostCategory
			= link_to edit_admin_post_category_path(@post_category), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.post_category.name")
				.display-value= @post_category.name
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_post_categories_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/post_categories/_listing.html.haml
%tr{ id: "row-#{post_category.id}" }
	- if can? :destroy_multiple, PostCategory
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_post_category_path(post_category), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{post_category.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{post_category.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{post_category.id}" }

		%td{style:"width: 30%"}
			= link_to "", admin_post_category_path(post_category, search: @query), remote: true, class: "show-row"
			%span
				= post_category.name
	- if can? :clone, PostCategory
		%td{style:"width: 5%"}
			= link_to admin_post_category_clone_path(post_category), class: "btn-floating waves-effect btn-flat" do
				= material_icon.md_24.content_copy.css_class("md-dark")
	%td{style:"width: 5%"}
		= link_to admin_post_category_path(post_category), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/post_categories/edit.html.haml
= title(t('keppler.titles.edit', model: "Post categories"))
= render 'form'

app/views/admin/post_categories/index.html.haml
= title(t('keppler.titles.index', model: "Post categories"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_post_category_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |post_category|
				= render 'listing', post_category: post_category
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.post_categories"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_post_category_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/post_categories/new.html.haml
= title(t('keppler.titles.new', model: "Post categories"))
= render 'form'

app/views/admin/post_categories/show.html.haml
= title(t('keppler.titles.show', model: "Post categories"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, PostCategory
				= link_to admin_post_category_path(@post_category), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, PostCategory
				= link_to edit_admin_post_category_path(@post_category), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_post_categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @post_category.id.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.name")
						.display-value.fs-body-1.tc-black-2= @post_category.name.to_s.humanize

app/views/admin/post_categories/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@post_category.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");